name: order_payments
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dropdown_button2: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.3
  http: ^0.13.5
  intl: ^0.18.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
